spring.application.name=PRODUCTS-SERVICE
server.port=8081

#configuration of eureka
eureka.client.service-url.defaultZone=${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka}
eureka.instance.prefer-ip-address=true

spring.profiles.active=dev