eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    # Explicitly verify the busrefresh component is active
    busrefresh:
      enabled: true
  health:
    probe:
      enabled: true
    config:
      enabled: true

PRODUCT_SERVICE_ID: "lb://PRODUCT-SERVICE"
CARTORDER_SERVICE_ID: "lb://CART-ORDER-SERVICE"
